version: '3.4'

services:


  orderdb:
    container_name: orderdb
    environment:
        darshu_PASSWORD: "darshu@1509"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"


  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

